### ISSUE TITLE
Front-End Visual Draft Website

### ISSUE THREAD

**Issue by MP018** [MP018/Jewelry-Store-Inventory#2]
**Tasks**
- [x] Figure out a color palette the client agrees with (Works with @ReeceC747 )
- [x] Find fonts and font hierarchy and layout
- [x] Draft a website outline on the tabs, webpages, buttons, where is where (Visual, doesn't need to be working)
- [x] Make a sample mockup (Visual, doesn't need to be working)
- [x] Present to Client eventually
